# Generated by Django 2.2 on 2020-01-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20200102_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodify',
            name='is_agree',
            field=models.BooleanField(default=False),
        ),
    ]
