# Generated by Django 2.2 on 2020-01-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_taskmodify_is_agree'),
    ]

    operations = [

    ]
