# Generated by Django 2.2 on 2020-01-10 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_taskquality'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='score',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.DO_NOTHING, to='task.TaskQuality'),
        ),
    ]
